//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_rbe : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabObject
        {
            get
            {
                return SteamVR_Actions.rbe_GrabObject;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.rbe_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuAndSelectLaser
        {
            get
            {
                return SteamVR_Actions.rbe_MenuAndSelectLaser;
            }
        }
        
        public virtual SteamVR_Action_Boolean TakeActionGeneric
        {
            get
            {
                return SteamVR_Actions.rbe_TakeActionGeneric;
            }
        }
        
        public virtual SteamVR_Action_Boolean TakeActionMovement
        {
            get
            {
                return SteamVR_Actions.rbe_TakeActionMovement;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.rbe_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.rbe_RightClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UpDownTouchpad
        {
            get
            {
                return SteamVR_Actions.rbe_UpDownTouchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpDownTouchpadPressed
        {
            get
            {
                return SteamVR_Actions.rbe_UpDownTouchpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean PreviewActionGeneric
        {
            get
            {
                return SteamVR_Actions.rbe_PreviewActionGeneric;
            }
        }
        
        public virtual SteamVR_Action_Single PreviewActionPull
        {
            get
            {
                return SteamVR_Actions.rbe_PreviewActionPull;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.rbe_Haptic;
            }
        }
    }
}
