//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_terraingenerate : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TouchpadPressed
        {
            get
            {
                return SteamVR_Actions.terraingenerate_TouchpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad_XY
        {
            get
            {
                return SteamVR_Actions.terraingenerate_Touchpad_XY;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabObject
        {
            get
            {
                return SteamVR_Actions.terraingenerate_GrabObject;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.terraingenerate_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean GeneratePoint
        {
            get
            {
                return SteamVR_Actions.terraingenerate_GeneratePoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadPreview
        {
            get
            {
                return SteamVR_Actions.terraingenerate_TouchpadPreview;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.terraingenerate_Haptic;
            }
        }
    }
}
